server:
    port: 8087

spring:
    application:
        name: search-service

    elasticsearch:
        uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}

    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        consumer:
            group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:search-service-cdc}
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
    cdc:
        jobs-topic: ${CDC_JOBS_TOPIC:job_db.public.jobs}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: always

logging:
    level:
        root: INFO
        vn.hoidanit.searchservice: DEBUG
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n'
        file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n'
    file:
        name: logs/search-service.log

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        try-it-out-enabled: true
        operations-sorter: method
        tags-sorter: alpha
    show-actuator: true

